#!/bin/bash

if [[ ! -d "$(pwd)/bash-aliases-framework" ]];then
  git clone git@github.com:nicolachoquet06250/bash-aliases-framework.git
fi

rm -rf "$(pwd)/bash-aliases-framework/.git/hooks/post-checkout"
ln -s "$(pwd)/bash-aliases-framework/.githooks/post-checkout" "$(pwd)/bash-aliases-framework/.git/hooks/post-checkout"
echo "${SUDO_PASSWD}" | sudo -S chmod +x "$(pwd)/bash-aliases-framework/.githooks/post-checkout"

# shellcheck disable=SC1090
. "$(pwd)/bash-aliases-framework/.git/hooks/post-checkout" "install-script"

if [[ ! -d "${HOME}/.bash-alias-clipboard" ]];then
  path=""
  if [[ "$1" == "install-script" ]];then
    path="/bash-alias-clipboard"
  fi
  ln -s "$(pwd)${path}" "${HOME}/.bash-alias-clipboard";
fi

file_path=".bash-alias-clipboard/.bash_aliases"
source="source \"\${HOME}/${file_path}\""
bash_aliases_path="${HOME}/.bash_aliases"

file_content="$(cat "${bash_aliases_path}")"
IFS=$'\n'
read -rd '' -a lines <<<"${file_content}"

if [[ "${lines[*]}" != *"$source"* ]];then
  echo "source \"\${HOME}/${file_path}\"" >> "${bash_aliases_path}"
fi