#!/bin/bash

echo "$(pwd)"

if {
#  [[ "$(type framework 2>&1)" =~ "non trouvé" ]] ||
#  [[ "$(type framework 2>&1)" =~ "not found" ]] ||
  [[ ! -d "$(pwd)/bash-aliases-framework" ]]
};then
  git clone git@github.com:nicolachoquet06250/bash-aliases-framework.git
  if {
      [[ -f "$(pwd)/bash-aliases-framework/.githooks/post-checkout" ]] &&
      [[ ! -f "$(pwd)/bash-aliases-framework/.git/hooks/post-checkout" ]]
  };then
    ln -s "$(pwd)/bash-aliases-framework/.githooks/post-checkout" "$(pwd)/bash-aliases-framework/.git/hooks/post-checkout"
  fi

  # shellcheck disable=SC1090
  . "$(pwd)/bash-aliases-framework/.git/hooks/post-checkout" "install-script"
fi

if [[ ! -d "${HOME}/.bash-alias-clipboard" ]];then
  path=""
  if [[ "$1" == "install-script" ]];then
    path="/bash-alias-clipboard"
  fi
  ln -s "$(pwd)${path}" "${HOME}/.bash-alias-clipboard";
fi

file_path=".bash-alias-clipboard/.bash_aliases"

source_1="source \"\${HOME}/${file_path}\""
source_2="source \"~/${file_path}\""

bash_aliases_path="${HOME}/.bash_aliases"
bash_aliases_content="$(cat "${bash_aliases_path}")"

if {
  [[ ! "${bash_aliases_content}" =~ $source_1 ]] &&
  [[ ! "${bash_aliases_content}" =~ $source_2 ]]
};then
  echo "source \"\${HOME}/${file_path}\"" >> "${bash_aliases_path}"
fi